# Generated by Django 5.1.7 on 2025-04-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_psychologist_groups_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='psychologist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.psychologist'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.psychologist'),
        ),
    ]
